include: "rules/common.smk"
include: "rules/utils.smk"
include: "rules/qc.smk"
include: "rules/trim.smk"
include: "rules/map.smk"
include: "rules/rawvc.smk"
include: "rules/variantfilter.smk"
include: "rules/popoolation.smk"
include: "rules/popoolation2.smk"


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"

rule all:
    input: unpack(all)
