db:
  ref: data/external/ref/scaffolds.fa
reads:
  readfile: config/reads.tsv
samples:
  individual: config/samples.individual.tsv
  pool: config/samples.pool.tsv
  ignore: ["PUR.HG00731", "PUR.HG00733", "YRI.NA19238", "PUR", "CHS.HG00512"]
datasources: config/datasources.tsv

workflow:
  trim: true
  regions:
    scaffolds:
      bed: data/external/ref/scaffolds.bed
      npart: 2
      ploidy: 2
  qc: ['picard', 'fastqc', 'jellyfish', 'sambamba', 'bcftools', 'qualimap']
