db:
  ref: data/external/ref/scaffolds.fa
reads:
  readfile: config/reads.tsv
samples:
  individual: config/samples.individual.tsv
  pool: config/samples.pool.tsv
  ignore: ["A", "PUR.HG00733", "YRI.NA19238", "PUR"]
datasources: config/datasources.tsv

workflow:
  trim: true
  regions:
    scaffolds:
      bed: data/external/ref/scaffolds.bed
      npart: 3
      ploidy: 2
