db:
  ref: data/external/ref/scaffolds.fa
  repeats: data/external/ref/scaffolds-targets.bed
reads:
  readfile: config/reads.tsv
samples:
  individual: config/samples.individual.tsv
  pool: config/samples.pool.tsv
  ignore: ["PUR.HG00731", "PUR.HG00733", "YRI.NA19238", "PUR", "CHS.HG00512"]
datasources: config/datasources.tsv

workflow:
  trim: true
  regions:
    scaffolds:
      bed: data/external/ref/scaffolds.bed
      npart: 2
      ploidy:
        common: 2
  qc: ['picard', 'fastqc', 'jellyfish', 'sambamba', 'bcftools', 'qualimap']


resources:
  popoolation_variance_sliding:
    options: --min-count 2 --min-coverage 6

analysis/gatk_best_practice_snp:
  description: >-
      GATK best practice analysis for snps. Hard filters are applied
      to get a high-quality call set.
  filters:
    gatk_select_snp:
      description: GATK select snp
      filter: gatk_select_variants
      options: --select-type-to-include SNP
    gatk_filter:
      description: GATK filter snps
      filter: gatk_jexl_filter_variants
      options: ["QD < 2.0", "MQ < 40.0", "FS > 60.0", "MQRankSum < -12.5", "ReadPosRankSum < -8.0", "SOR > 3.0"]
  plots:
    pca:
      script: manticore-plotvcf.py
      type: pca

analysis/popoolation_best_practice:
  description: >-
      popoolation best practice. Filter pileups by indels and
      subsample data to target a given coverage.
  samples:
    - CHS
  filters:
    filter_pileup_by_indels:
      description: filter pileup by indel gtf
      filter: popoolation_filter_pileup_by_gtf
      options: ""
    subsample_pileup:
      description: subsample pileup by coverage
      filter: popoolation_subsample_pileup
      options: --method withoutreplace --fastq-type sanger --target-coverage 2 --max-coverage 10 --min-qual 20
  statistics:
    variance_sliding:
      description: Popoolation variance sliding analysis
      statistic: ['pi', 'theta']
      window_size: [10000, 50000]
      step_size: [10000, 50000]
      engine: popoolation
