db:
  ref: data/external/ref/scaffolds.fa
  repeats: data/external/ref/scaffolds-targets.bed
reads:
  readfile: config/reads.tsv
samples:
  individual: config/samples.individual.tsv
  pool: config/samples.pool.tsv
  ignore: ["PUR.HG00731", "PUR.HG00733", "YRI.NA19238", "PUR", "CHS.HG00512"]

workflow:
  trim: true
  regions:
    scaffolds:
      bed: data/external/ref/scaffolds.bed
      npart: 2
      ploidy:
        common: 2
  qc: ['picard', 'fastqc', 'jellyfish', 'sambamba', 'bcftools', 'qualimap']

resources.default:
  java_options: -Xmx1024M

resources:
  popoolation_variance_sliding:
    options: --min-count 2 --min-coverage 6

analysis/gatk_best_practice_snp:
  description: >-
    GATK best practice analysis for snps. Hard filters are applied
    to get a high-quality call set.
  group: ind
  tool: gatk
  filters:
    - select:
        options: --select-type-to-include SNP
    - filter:
        filters: ["QD < 2.0", "MQ < 40.0", "FS > 60.0", "MQRankSum < -12.5", "ReadPosRankSum < -8.0", "SOR > 3.0"]
    - concat:
        tool: bcftools


analysis/popoolation_best_practice:
  description: >-
    Popoolation best practice analysis of individual pools.
  group: pool
  tool: popoolation
  filters:
    - mask:
        description: Remove indels
    - filter:
        options: --method withoutreplace --fastq-type sanger --target-coverage 2 --max-coverage 10 --min-qual 20
  statistics:
    - windowed_statistic:
        statistic: ["pi", "theta"]
        window_size: [10000]
        options: --min-count 2 --min-coverage 6 --min-covered-fraction .1 --fastq-type sanger


analysis/popoolation2_best_practice:
  description: >-
    Popoolation2 best practice analysis of combined pools.
  group: pool
  tool: popoolation2
  filters:
    - mask:
        description: Remove indels
    - select:
    - filter:
        options: --max-coverage 8 --target-coverage 1 --method withoutreplace
  statistics:
    - windowed_statistic:
        statistic: ["fst", "fet"]
        window_size: [10000]
        options: --max-coverage 5
    - plain_statistic:
        statistic: ["rc", "pwc"]
        options: --max-coverage 5
