db:
  ref: data/external/ref/scaffolds.fa
  repeats: data/external/ref/scaffolds-targets.bed
reads:
  readfile: config/reads.tsv
samples:
  individual: config/samples.individual.tsv
  pool: config/samples.pool.tsv
  ignore: ["PUR.HG00731", "PUR.HG00733", "YRI.NA19238", "PUR", "CHS.HG00512"]
datasources: config/datasources.tsv

workflow:
  trim: true
  regions:
    scaffolds:
      bed: data/external/ref/scaffolds.bed
      npart: 2
      ploidy:
        common: 2
  qc: ['picard', 'fastqc', 'jellyfish', 'sambamba', 'bcftools', 'qualimap']


resources:
  popoolation_subsample_pileup:
    options: --method withoutreplace --fastq-type sanger --target-coverage 1 --max-coverage 10 --min-qual 20
