$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: object
    default: {}
    properties:
      individual:
        type: [string, 'null']
        format: uri
        description: samplesheet for individuals
        default: null
      pool:
        type: [string, 'null']
        format: uri
        description: samplesheet for pools
        default: null
      ignore:
        type: array
        description: list of samples (SM) to exclude in analysis
        uniqueItems: true
        default: []
        items:
          type: string
  reads:
    type: object
    default: {}
    properties:
      readfile:
        type: [string, 'null']
        description: file containing reads
        default: null
      read_group_fmt:
        type: string
        description: >
          format string for readgroup. Express as python miniformat
          string using columns in reads file.
        default: "{SM}_{unit}"
        format: uri
        examples:
          - "{SM}"
          - "{SM}_{unit}"
          - "{SM}_{PU}"
      ignore:
        type: array
        description: list of reads (unit column) to exclude in analysis
        uniqueItems: true
        default: []
        items:
          type: string
  datasources:
    type: [string, 'null']
    default: null
    format: uri
  fs:
    $ref: "definitions.schema.yaml#/definitions/fs"
    default: {}
  workflow:
    $ref: "definitions.schema.yaml#/definitions/workflow"
    default: {}
  db:
    $ref: "definitions.schema.yaml#/definitions/db"
    default: {}

  ##############################
  # Resources and rules
  ##############################
  resources.default:
    $ref: "definitions.schema.yaml#/definitions/resources.default"
    default: {}

  resources:
    $ref: "definitions.schema.yaml#/definitions/resources"
    default: {}

##############################
# analysis sets
##############################
patternProperties:
  '^resources/[a-zA-Z\.\-_0-9/\{\}]+':
    type: object
    $ref: "#/definitions/resources"
    description: >-
        resources configuration for specific regions, treatments and
        other factors
  '^analysis/[0-9a-zA-Z-_]+':
    type: object
    default:
      input: null
    description: >-
        analysis/ properties define separate analyses that will be
        applied to input data. By default input data will be the raw
        variant calls. There are three properties filters, statistics,
        and plots that define different data operations. The output
        directories are numbered according to occurence.
    properties:
      input:
        type: [string, array, 'null']
        default: null
        items:
          type: string
          uniqueItems: true
      filters:
        description: >-
          The filters property lists what filters to apply to input
          data. They are applied sequentially, in the case that multiple
          filters are defined.
        default: {}
        $ref: "definitions.schema.yaml#/definitions/filters"
      statistics:
        description: >-
          The statistics property lists what statistics to apply to
          the filtered data
        default: {}
        $ref: "definitions.schema.yaml#/definitions/statistics"
      plots:
        description: >-
          The plots property lists plots to apply to statistics
        default: {}
        $ref: "definitions.schema.yaml#/definitions/plots"
    required: ['input']
    additionalProperties: false

additionalProperties: false
