$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: object
    description: samplesheet files
    default: {}
    properties:
      individual:
        type: [string, 'null']
        format: uri
        description: samplesheet for individuals
        default: null
      pool:
        type: [string, 'null']
        format: uri
        description: samplesheet for pools
        default: null
      ignore:
        $ref: "definitions.schema.yaml#/definitions/unitids"
        description: list of samples (SM) to exclude in analysis
        default: []
  reads:
    type: object
    default: {}
    properties:
      readfile:
        type: [string, 'null']
        description: file containing reads
        default: null
      read_group_fmt:
        type: string
        description: >
          format string for readgroup. Express as python miniformat
          string using columns in reads file.
        default: "{SM}_{unit}"
        format: uri
        examples:
          - "{SM}"
          - "{SM}_{unit}"
          - "{SM}_{PU}"
      ignore:
        $ref: "definitions.schema.yaml#/definitions/unitids"
        description: list of reads (unit column) to exclude in analysis
        default: []
  fs:
    $ref: "definitions.schema.yaml#/definitions/fs"
    default: {}
  workflow:
    $ref: "definitions.schema.yaml#/definitions/workflow"
    default: {}
  db:
    $ref: "definitions.schema.yaml#/definitions/db"
    default: {}

  ##############################
  # Rule configuration
  ##############################
  rules:
    $ref: "definitions.schema.yaml#/definitions/rules.config"
    default: {}


##############################
# analysis sets
##############################
patternProperties:
  '^analysis/[0-9a-zA-Z-_]+':
    type: object
    $ref: "analysisset.schema.yaml#/definitions/analysis"
    description: >-
        analysis/ properties define separate analyses that will be
        applied to input data. By default input data will be the raw
        variant calls. There are three properties filters, statistics,
        and plots that define different data operations. The output
        directories are numbered according to occurence.
