name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Remove failing qualimap from tests
      run: "sed -i -e \"s/, 'qualimap'//g\" .test/config/config.yaml"
    - name: Install workflow environments
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --wrapper-prefix file:///github/workspace/workflow/wrappers --conda-create-envs-only"
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --wrapper-prefix file:///github/workspace/workflow/wrappers"
        stagein: 'mamba install -y -c conda-forge subversion svn snakemake-wrapper-utils;
         ./workflow/scripts/manticore_install_popoolation.py --snakefile workflow/Snakefile --env-dir .test/.snakemake/conda'
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.21.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip --wrapper-prefix file:///github/workspace/workflow/wrappers"
